/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRedirectRouteImport } from './routes/sign-in-redirect'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as CollabInviteRouteImport } from './routes/collab-invite'
import { Route as AccountRouteImport } from './routes/account'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as VerifySuccessRouteImport } from './routes/verify/success'
import { Route as VerifyErrorRouteImport } from './routes/verify/error'
import { Route as SetupVrchatRouteImport } from './routes/setup/vrchat'
import { Route as SetupPayhipRouteImport } from './routes/setup/payhip'
import { Route as SetupLemonsqueezyRouteImport } from './routes/setup/lemonsqueezy'
import { Route as SetupJinxxyRouteImport } from './routes/setup/jinxxy'
import { Route as SetupDiscordRoleRouteImport } from './routes/setup/discord-role'
import { Route as OauthLoginRouteImport } from './routes/oauth/login'
import { Route as OauthErrorRouteImport } from './routes/oauth/error'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as LegalTermsOfServiceRouteImport } from './routes/legal/terms-of-service'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/legal/privacy-policy'
import { Route as InstallSuccessRouteImport } from './routes/install/success'
import { Route as InstallErrorRouteImport } from './routes/install/error'
import { Route as DashboardServerRulesRouteImport } from './routes/dashboard/server-rules'
import { Route as DashboardIntegrationsRouteImport } from './routes/dashboard/integrations'
import { Route as DashboardCollaborationRouteImport } from './routes/dashboard/collaboration'
import { Route as DashboardCertificatesRouteImport } from './routes/dashboard/certificates'
import { Route as DashboardAuditLogsRouteImport } from './routes/dashboard/audit-logs'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AccountPrivacyRouteImport } from './routes/account/privacy'
import { Route as AccountLicensesRouteImport } from './routes/account/licenses'
import { Route as AccountConnectionsRouteImport } from './routes/account/connections'
import { Route as AccountCertificatesRouteImport } from './routes/account/certificates'
import { Route as AccountAuthorizedAppsRouteImport } from './routes/account/authorized-apps'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignInRedirectRoute = SignInRedirectRouteImport.update({
  id: '/sign-in-redirect',
  path: '/sign-in-redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabInviteRoute = CollabInviteRouteImport.update({
  id: '/collab-invite',
  path: '/collab-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const VerifySuccessRoute = VerifySuccessRouteImport.update({
  id: '/verify/success',
  path: '/verify/success',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyErrorRoute = VerifyErrorRouteImport.update({
  id: '/verify/error',
  path: '/verify/error',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupVrchatRoute = SetupVrchatRouteImport.update({
  id: '/setup/vrchat',
  path: '/setup/vrchat',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupPayhipRoute = SetupPayhipRouteImport.update({
  id: '/setup/payhip',
  path: '/setup/payhip',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupLemonsqueezyRoute = SetupLemonsqueezyRouteImport.update({
  id: '/setup/lemonsqueezy',
  path: '/setup/lemonsqueezy',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupJinxxyRoute = SetupJinxxyRouteImport.update({
  id: '/setup/jinxxy',
  path: '/setup/jinxxy',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupDiscordRoleRoute = SetupDiscordRoleRouteImport.update({
  id: '/setup/discord-role',
  path: '/setup/discord-role',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthLoginRoute = OauthLoginRouteImport.update({
  id: '/oauth/login',
  path: '/oauth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthErrorRoute = OauthErrorRouteImport.update({
  id: '/oauth/error',
  path: '/oauth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsOfServiceRoute = LegalTermsOfServiceRouteImport.update({
  id: '/legal/terms-of-service',
  path: '/legal/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/legal/privacy-policy',
  path: '/legal/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallSuccessRoute = InstallSuccessRouteImport.update({
  id: '/install/success',
  path: '/install/success',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallErrorRoute = InstallErrorRouteImport.update({
  id: '/install/error',
  path: '/install/error',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardServerRulesRoute = DashboardServerRulesRouteImport.update({
  id: '/server-rules',
  path: '/server-rules',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntegrationsRoute = DashboardIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCollaborationRoute = DashboardCollaborationRouteImport.update({
  id: '/collaboration',
  path: '/collaboration',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCertificatesRoute = DashboardCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditLogsRoute = DashboardAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPrivacyRoute = AccountPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AccountRoute,
} as any)
const AccountLicensesRoute = AccountLicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => AccountRoute,
} as any)
const AccountConnectionsRoute = AccountConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AccountRoute,
} as any)
const AccountCertificatesRoute = AccountCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAuthorizedAppsRoute = AccountAuthorizedAppsRouteImport.update({
  id: '/authorized-apps',
  path: '/authorized-apps',
  getParentRoute: () => AccountRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRouteWithChildren
  '/collab-invite': typeof CollabInviteRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-in-redirect': typeof SignInRedirectRoute
  '/account/authorized-apps': typeof AccountAuthorizedAppsRoute
  '/account/certificates': typeof AccountCertificatesRoute
  '/account/connections': typeof AccountConnectionsRoute
  '/account/licenses': typeof AccountLicensesRoute
  '/account/privacy': typeof AccountPrivacyRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard/audit-logs': typeof DashboardAuditLogsRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/collaboration': typeof DashboardCollaborationRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/server-rules': typeof DashboardServerRulesRoute
  '/install/error': typeof InstallErrorRoute
  '/install/success': typeof InstallSuccessRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/error': typeof OauthErrorRoute
  '/oauth/login': typeof OauthLoginRoute
  '/setup/discord-role': typeof SetupDiscordRoleRoute
  '/setup/jinxxy': typeof SetupJinxxyRoute
  '/setup/lemonsqueezy': typeof SetupLemonsqueezyRoute
  '/setup/payhip': typeof SetupPayhipRoute
  '/setup/vrchat': typeof SetupVrchatRoute
  '/verify/error': typeof VerifyErrorRoute
  '/verify/success': typeof VerifySuccessRoute
  '/account/': typeof AccountIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/collab-invite': typeof CollabInviteRoute
  '/connect': typeof ConnectRoute
  '/sign-in': typeof SignInRoute
  '/sign-in-redirect': typeof SignInRedirectRoute
  '/account/authorized-apps': typeof AccountAuthorizedAppsRoute
  '/account/certificates': typeof AccountCertificatesRoute
  '/account/connections': typeof AccountConnectionsRoute
  '/account/licenses': typeof AccountLicensesRoute
  '/account/privacy': typeof AccountPrivacyRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard/audit-logs': typeof DashboardAuditLogsRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/collaboration': typeof DashboardCollaborationRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/server-rules': typeof DashboardServerRulesRoute
  '/install/error': typeof InstallErrorRoute
  '/install/success': typeof InstallSuccessRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/error': typeof OauthErrorRoute
  '/oauth/login': typeof OauthLoginRoute
  '/setup/discord-role': typeof SetupDiscordRoleRoute
  '/setup/jinxxy': typeof SetupJinxxyRoute
  '/setup/lemonsqueezy': typeof SetupLemonsqueezyRoute
  '/setup/payhip': typeof SetupPayhipRoute
  '/setup/vrchat': typeof SetupVrchatRoute
  '/verify/error': typeof VerifyErrorRoute
  '/verify/success': typeof VerifySuccessRoute
  '/account': typeof AccountIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRouteWithChildren
  '/collab-invite': typeof CollabInviteRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-in-redirect': typeof SignInRedirectRoute
  '/account/authorized-apps': typeof AccountAuthorizedAppsRoute
  '/account/certificates': typeof AccountCertificatesRoute
  '/account/connections': typeof AccountConnectionsRoute
  '/account/licenses': typeof AccountLicensesRoute
  '/account/privacy': typeof AccountPrivacyRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard/audit-logs': typeof DashboardAuditLogsRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/collaboration': typeof DashboardCollaborationRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/server-rules': typeof DashboardServerRulesRoute
  '/install/error': typeof InstallErrorRoute
  '/install/success': typeof InstallSuccessRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/error': typeof OauthErrorRoute
  '/oauth/login': typeof OauthLoginRoute
  '/setup/discord-role': typeof SetupDiscordRoleRoute
  '/setup/jinxxy': typeof SetupJinxxyRoute
  '/setup/lemonsqueezy': typeof SetupLemonsqueezyRoute
  '/setup/payhip': typeof SetupPayhipRoute
  '/setup/vrchat': typeof SetupVrchatRoute
  '/verify/error': typeof VerifyErrorRoute
  '/verify/success': typeof VerifySuccessRoute
  '/account/': typeof AccountIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/account'
    | '/collab-invite'
    | '/connect'
    | '/dashboard'
    | '/sign-in'
    | '/sign-in-redirect'
    | '/account/authorized-apps'
    | '/account/certificates'
    | '/account/connections'
    | '/account/licenses'
    | '/account/privacy'
    | '/api/$'
    | '/dashboard/audit-logs'
    | '/dashboard/certificates'
    | '/dashboard/collaboration'
    | '/dashboard/integrations'
    | '/dashboard/server-rules'
    | '/install/error'
    | '/install/success'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/oauth/consent'
    | '/oauth/error'
    | '/oauth/login'
    | '/setup/discord-role'
    | '/setup/jinxxy'
    | '/setup/lemonsqueezy'
    | '/setup/payhip'
    | '/setup/vrchat'
    | '/verify/error'
    | '/verify/success'
    | '/account/'
    | '/dashboard/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/collab-invite'
    | '/connect'
    | '/sign-in'
    | '/sign-in-redirect'
    | '/account/authorized-apps'
    | '/account/certificates'
    | '/account/connections'
    | '/account/licenses'
    | '/account/privacy'
    | '/api/$'
    | '/dashboard/audit-logs'
    | '/dashboard/certificates'
    | '/dashboard/collaboration'
    | '/dashboard/integrations'
    | '/dashboard/server-rules'
    | '/install/error'
    | '/install/success'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/oauth/consent'
    | '/oauth/error'
    | '/oauth/login'
    | '/setup/discord-role'
    | '/setup/jinxxy'
    | '/setup/lemonsqueezy'
    | '/setup/payhip'
    | '/setup/vrchat'
    | '/verify/error'
    | '/verify/success'
    | '/account'
    | '/dashboard'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/account'
    | '/collab-invite'
    | '/connect'
    | '/dashboard'
    | '/sign-in'
    | '/sign-in-redirect'
    | '/account/authorized-apps'
    | '/account/certificates'
    | '/account/connections'
    | '/account/licenses'
    | '/account/privacy'
    | '/api/$'
    | '/dashboard/audit-logs'
    | '/dashboard/certificates'
    | '/dashboard/collaboration'
    | '/dashboard/integrations'
    | '/dashboard/server-rules'
    | '/install/error'
    | '/install/success'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/oauth/consent'
    | '/oauth/error'
    | '/oauth/login'
    | '/setup/discord-role'
    | '/setup/jinxxy'
    | '/setup/lemonsqueezy'
    | '/setup/payhip'
    | '/setup/vrchat'
    | '/verify/error'
    | '/verify/success'
    | '/account/'
    | '/dashboard/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AccountRoute: typeof AccountRouteWithChildren
  CollabInviteRoute: typeof CollabInviteRoute
  ConnectRoute: typeof ConnectRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignInRedirectRoute: typeof SignInRedirectRoute
  ApiSplatRoute: typeof ApiSplatRoute
  InstallErrorRoute: typeof InstallErrorRoute
  InstallSuccessRoute: typeof InstallSuccessRoute
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
  LegalTermsOfServiceRoute: typeof LegalTermsOfServiceRoute
  OauthConsentRoute: typeof OauthConsentRoute
  OauthErrorRoute: typeof OauthErrorRoute
  OauthLoginRoute: typeof OauthLoginRoute
  SetupDiscordRoleRoute: typeof SetupDiscordRoleRoute
  SetupJinxxyRoute: typeof SetupJinxxyRoute
  SetupLemonsqueezyRoute: typeof SetupLemonsqueezyRoute
  SetupPayhipRoute: typeof SetupPayhipRoute
  SetupVrchatRoute: typeof SetupVrchatRoute
  VerifyErrorRoute: typeof VerifyErrorRoute
  VerifySuccessRoute: typeof VerifySuccessRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in-redirect': {
      id: '/sign-in-redirect'
      path: '/sign-in-redirect'
      fullPath: '/sign-in-redirect'
      preLoaderRoute: typeof SignInRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab-invite': {
      id: '/collab-invite'
      path: '/collab-invite'
      fullPath: '/collab-invite'
      preLoaderRoute: typeof CollabInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/verify/success': {
      id: '/verify/success'
      path: '/verify/success'
      fullPath: '/verify/success'
      preLoaderRoute: typeof VerifySuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/error': {
      id: '/verify/error'
      path: '/verify/error'
      fullPath: '/verify/error'
      preLoaderRoute: typeof VerifyErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/vrchat': {
      id: '/setup/vrchat'
      path: '/setup/vrchat'
      fullPath: '/setup/vrchat'
      preLoaderRoute: typeof SetupVrchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/payhip': {
      id: '/setup/payhip'
      path: '/setup/payhip'
      fullPath: '/setup/payhip'
      preLoaderRoute: typeof SetupPayhipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/lemonsqueezy': {
      id: '/setup/lemonsqueezy'
      path: '/setup/lemonsqueezy'
      fullPath: '/setup/lemonsqueezy'
      preLoaderRoute: typeof SetupLemonsqueezyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/jinxxy': {
      id: '/setup/jinxxy'
      path: '/setup/jinxxy'
      fullPath: '/setup/jinxxy'
      preLoaderRoute: typeof SetupJinxxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/discord-role': {
      id: '/setup/discord-role'
      path: '/setup/discord-role'
      fullPath: '/setup/discord-role'
      preLoaderRoute: typeof SetupDiscordRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/login': {
      id: '/oauth/login'
      path: '/oauth/login'
      fullPath: '/oauth/login'
      preLoaderRoute: typeof OauthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/error': {
      id: '/oauth/error'
      path: '/oauth/error'
      fullPath: '/oauth/error'
      preLoaderRoute: typeof OauthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms-of-service': {
      id: '/legal/terms-of-service'
      path: '/legal/terms-of-service'
      fullPath: '/legal/terms-of-service'
      preLoaderRoute: typeof LegalTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install/success': {
      id: '/install/success'
      path: '/install/success'
      fullPath: '/install/success'
      preLoaderRoute: typeof InstallSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install/error': {
      id: '/install/error'
      path: '/install/error'
      fullPath: '/install/error'
      preLoaderRoute: typeof InstallErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/server-rules': {
      id: '/dashboard/server-rules'
      path: '/server-rules'
      fullPath: '/dashboard/server-rules'
      preLoaderRoute: typeof DashboardServerRulesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/integrations': {
      id: '/dashboard/integrations'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof DashboardIntegrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/collaboration': {
      id: '/dashboard/collaboration'
      path: '/collaboration'
      fullPath: '/dashboard/collaboration'
      preLoaderRoute: typeof DashboardCollaborationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/certificates': {
      id: '/dashboard/certificates'
      path: '/certificates'
      fullPath: '/dashboard/certificates'
      preLoaderRoute: typeof DashboardCertificatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit-logs': {
      id: '/dashboard/audit-logs'
      path: '/audit-logs'
      fullPath: '/dashboard/audit-logs'
      preLoaderRoute: typeof DashboardAuditLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/privacy': {
      id: '/account/privacy'
      path: '/privacy'
      fullPath: '/account/privacy'
      preLoaderRoute: typeof AccountPrivacyRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/licenses': {
      id: '/account/licenses'
      path: '/licenses'
      fullPath: '/account/licenses'
      preLoaderRoute: typeof AccountLicensesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/connections': {
      id: '/account/connections'
      path: '/connections'
      fullPath: '/account/connections'
      preLoaderRoute: typeof AccountConnectionsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/certificates': {
      id: '/account/certificates'
      path: '/certificates'
      fullPath: '/account/certificates'
      preLoaderRoute: typeof AccountCertificatesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/authorized-apps': {
      id: '/account/authorized-apps'
      path: '/authorized-apps'
      fullPath: '/account/authorized-apps'
      preLoaderRoute: typeof AccountAuthorizedAppsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountAuthorizedAppsRoute: typeof AccountAuthorizedAppsRoute
  AccountCertificatesRoute: typeof AccountCertificatesRoute
  AccountConnectionsRoute: typeof AccountConnectionsRoute
  AccountLicensesRoute: typeof AccountLicensesRoute
  AccountPrivacyRoute: typeof AccountPrivacyRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAuthorizedAppsRoute: AccountAuthorizedAppsRoute,
  AccountCertificatesRoute: AccountCertificatesRoute,
  AccountConnectionsRoute: AccountConnectionsRoute,
  AccountLicensesRoute: AccountLicensesRoute,
  AccountPrivacyRoute: AccountPrivacyRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface DashboardRouteChildren {
  DashboardAuditLogsRoute: typeof DashboardAuditLogsRoute
  DashboardCertificatesRoute: typeof DashboardCertificatesRoute
  DashboardCollaborationRoute: typeof DashboardCollaborationRoute
  DashboardIntegrationsRoute: typeof DashboardIntegrationsRoute
  DashboardServerRulesRoute: typeof DashboardServerRulesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAuditLogsRoute: DashboardAuditLogsRoute,
  DashboardCertificatesRoute: DashboardCertificatesRoute,
  DashboardCollaborationRoute: DashboardCollaborationRoute,
  DashboardIntegrationsRoute: DashboardIntegrationsRoute,
  DashboardServerRulesRoute: DashboardServerRulesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AccountRoute: AccountRouteWithChildren,
  CollabInviteRoute: CollabInviteRoute,
  ConnectRoute: ConnectRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SignInRoute: SignInRoute,
  SignInRedirectRoute: SignInRedirectRoute,
  ApiSplatRoute: ApiSplatRoute,
  InstallErrorRoute: InstallErrorRoute,
  InstallSuccessRoute: InstallSuccessRoute,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
  LegalTermsOfServiceRoute: LegalTermsOfServiceRoute,
  OauthConsentRoute: OauthConsentRoute,
  OauthErrorRoute: OauthErrorRoute,
  OauthLoginRoute: OauthLoginRoute,
  SetupDiscordRoleRoute: SetupDiscordRoleRoute,
  SetupJinxxyRoute: SetupJinxxyRoute,
  SetupLemonsqueezyRoute: SetupLemonsqueezyRoute,
  SetupPayhipRoute: SetupPayhipRoute,
  SetupVrchatRoute: SetupVrchatRoute,
  VerifyErrorRoute: VerifyErrorRoute,
  VerifySuccessRoute: VerifySuccessRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
