/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRedirectRouteImport } from './routes/sign-in-redirect'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as CollabInviteRouteImport } from './routes/collab-invite'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifySuccessRouteImport } from './routes/verify/success'
import { Route as VerifyErrorRouteImport } from './routes/verify/error'
import { Route as SetupVrchatRouteImport } from './routes/setup/vrchat'
import { Route as SetupPayhipRouteImport } from './routes/setup/payhip'
import { Route as SetupLemonsqueezyRouteImport } from './routes/setup/lemonsqueezy'
import { Route as SetupJinxxyRouteImport } from './routes/setup/jinxxy'
import { Route as SetupDiscordRoleRouteImport } from './routes/setup/discord-role'
import { Route as OauthLoginRouteImport } from './routes/oauth/login'
import { Route as OauthErrorRouteImport } from './routes/oauth/error'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as LegalTermsOfServiceRouteImport } from './routes/legal/terms-of-service'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/legal/privacy-policy'
import { Route as InstallSuccessRouteImport } from './routes/install/success'
import { Route as InstallErrorRouteImport } from './routes/install/error'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account/index'
import { Route as OauthCallbackItchioRouteImport } from './routes/oauth/callback/itchio'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedVerifyPurchaseRouteImport } from './routes/_authenticated/verify/purchase'
import { Route as AuthenticatedDashboardServerRulesRouteImport } from './routes/_authenticated/dashboard/server-rules'
import { Route as AuthenticatedDashboardPackagesRouteImport } from './routes/_authenticated/dashboard/packages'
import { Route as AuthenticatedDashboardIntegrationsRouteImport } from './routes/_authenticated/dashboard/integrations'
import { Route as AuthenticatedDashboardForensicsRouteImport } from './routes/_authenticated/dashboard/forensics'
import { Route as AuthenticatedDashboardCollaborationRouteImport } from './routes/_authenticated/dashboard/collaboration'
import { Route as AuthenticatedDashboardCertificatesRouteImport } from './routes/_authenticated/dashboard/certificates'
import { Route as AuthenticatedDashboardBillingRouteImport } from './routes/_authenticated/dashboard/billing'
import { Route as AuthenticatedDashboardAuditLogsRouteImport } from './routes/_authenticated/dashboard/audit-logs'
import { Route as AuthenticatedAccountVerifyRouteImport } from './routes/_authenticated/account/verify'
import { Route as AuthenticatedAccountPrivacyRouteImport } from './routes/_authenticated/account/privacy'
import { Route as AuthenticatedAccountLicensesRouteImport } from './routes/_authenticated/account/licenses'
import { Route as AuthenticatedAccountConnectionsRouteImport } from './routes/_authenticated/account/connections'
import { Route as AuthenticatedAccountCertificatesRouteImport } from './routes/_authenticated/account/certificates'
import { Route as AuthenticatedAccountAuthorizedAppsRouteImport } from './routes/_authenticated/account/authorized-apps'

const SignInRedirectRoute = SignInRedirectRouteImport.update({
  id: '/sign-in-redirect',
  path: '/sign-in-redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabInviteRoute = CollabInviteRouteImport.update({
  id: '/collab-invite',
  path: '/collab-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifySuccessRoute = VerifySuccessRouteImport.update({
  id: '/verify/success',
  path: '/verify/success',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyErrorRoute = VerifyErrorRouteImport.update({
  id: '/verify/error',
  path: '/verify/error',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupVrchatRoute = SetupVrchatRouteImport.update({
  id: '/setup/vrchat',
  path: '/setup/vrchat',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/setup/vrchat.lazy').then((d) => d.Route))
const SetupPayhipRoute = SetupPayhipRouteImport.update({
  id: '/setup/payhip',
  path: '/setup/payhip',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/setup/payhip.lazy').then((d) => d.Route))
const SetupLemonsqueezyRoute = SetupLemonsqueezyRouteImport.update({
  id: '/setup/lemonsqueezy',
  path: '/setup/lemonsqueezy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/setup/lemonsqueezy.lazy').then((d) => d.Route),
)
const SetupJinxxyRoute = SetupJinxxyRouteImport.update({
  id: '/setup/jinxxy',
  path: '/setup/jinxxy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/setup/jinxxy.lazy').then((d) => d.Route))
const SetupDiscordRoleRoute = SetupDiscordRoleRouteImport.update({
  id: '/setup/discord-role',
  path: '/setup/discord-role',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthLoginRoute = OauthLoginRouteImport.update({
  id: '/oauth/login',
  path: '/oauth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthErrorRoute = OauthErrorRouteImport.update({
  id: '/oauth/error',
  path: '/oauth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/oauth/consent.lazy').then((d) => d.Route))
const LegalTermsOfServiceRoute = LegalTermsOfServiceRouteImport.update({
  id: '/legal/terms-of-service',
  path: '/legal/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/legal/privacy-policy',
  path: '/legal/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallSuccessRoute = InstallSuccessRouteImport.update({
  id: '/install/success',
  path: '/install/success',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/install/success.lazy').then((d) => d.Route),
)
const InstallErrorRoute = InstallErrorRouteImport.update({
  id: '/install/error',
  path: '/install/error',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/install/error.lazy').then((d) => d.Route))
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/dashboard.lazy').then((d) => d.Route),
)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/account.lazy').then((d) => d.Route),
)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/index.lazy').then((d) => d.Route),
  )
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/account/index.lazy').then((d) => d.Route),
  )
const OauthCallbackItchioRoute = OauthCallbackItchioRouteImport.update({
  id: '/oauth/callback/itchio',
  path: '/oauth/callback/itchio',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/oauth/callback/itchio.lazy').then((d) => d.Route),
)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVerifyPurchaseRoute =
  AuthenticatedVerifyPurchaseRouteImport.update({
    id: '/verify/purchase',
    path: '/verify/purchase',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/verify/purchase.lazy').then((d) => d.Route),
  )
const AuthenticatedDashboardServerRulesRoute =
  AuthenticatedDashboardServerRulesRouteImport.update({
    id: '/server-rules',
    path: '/server-rules',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/server-rules.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardPackagesRoute =
  AuthenticatedDashboardPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/packages.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardIntegrationsRoute =
  AuthenticatedDashboardIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/integrations.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardForensicsRoute =
  AuthenticatedDashboardForensicsRouteImport.update({
    id: '/forensics',
    path: '/forensics',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/forensics.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardCollaborationRoute =
  AuthenticatedDashboardCollaborationRouteImport.update({
    id: '/collaboration',
    path: '/collaboration',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/collaboration.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardCertificatesRoute =
  AuthenticatedDashboardCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/certificates.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardBillingRoute =
  AuthenticatedDashboardBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/billing.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardAuditLogsRoute =
  AuthenticatedDashboardAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/audit-logs.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedAccountVerifyRoute =
  AuthenticatedAccountVerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/account/verify.lazy').then((d) => d.Route),
  )
const AuthenticatedAccountPrivacyRoute =
  AuthenticatedAccountPrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/account/privacy.lazy').then((d) => d.Route),
  )
const AuthenticatedAccountLicensesRoute =
  AuthenticatedAccountLicensesRouteImport.update({
    id: '/licenses',
    path: '/licenses',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/account/licenses.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedAccountConnectionsRoute =
  AuthenticatedAccountConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/account/connections.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedAccountCertificatesRoute =
  AuthenticatedAccountCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/account/certificates.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedAccountAuthorizedAppsRoute =
  AuthenticatedAccountAuthorizedAppsRouteImport.update({
    id: '/authorized-apps',
    path: '/authorized-apps',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/account/authorized-apps.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/collab-invite': typeof CollabInviteRoute
  '/connect': typeof ConnectRoute
  '/sign-in': typeof SignInRoute
  '/sign-in-redirect': typeof SignInRedirectRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/install/error': typeof InstallErrorRoute
  '/install/success': typeof InstallSuccessRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/error': typeof OauthErrorRoute
  '/oauth/login': typeof OauthLoginRoute
  '/setup/discord-role': typeof SetupDiscordRoleRoute
  '/setup/jinxxy': typeof SetupJinxxyRoute
  '/setup/lemonsqueezy': typeof SetupLemonsqueezyRoute
  '/setup/payhip': typeof SetupPayhipRoute
  '/setup/vrchat': typeof SetupVrchatRoute
  '/verify/error': typeof VerifyErrorRoute
  '/verify/success': typeof VerifySuccessRoute
  '/account/authorized-apps': typeof AuthenticatedAccountAuthorizedAppsRoute
  '/account/certificates': typeof AuthenticatedAccountCertificatesRoute
  '/account/connections': typeof AuthenticatedAccountConnectionsRoute
  '/account/licenses': typeof AuthenticatedAccountLicensesRoute
  '/account/privacy': typeof AuthenticatedAccountPrivacyRoute
  '/account/verify': typeof AuthenticatedAccountVerifyRoute
  '/dashboard/audit-logs': typeof AuthenticatedDashboardAuditLogsRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/dashboard/certificates': typeof AuthenticatedDashboardCertificatesRoute
  '/dashboard/collaboration': typeof AuthenticatedDashboardCollaborationRoute
  '/dashboard/forensics': typeof AuthenticatedDashboardForensicsRoute
  '/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/dashboard/packages': typeof AuthenticatedDashboardPackagesRoute
  '/dashboard/server-rules': typeof AuthenticatedDashboardServerRulesRoute
  '/verify/purchase': typeof AuthenticatedVerifyPurchaseRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/oauth/callback/itchio': typeof OauthCallbackItchioRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/collab-invite': typeof CollabInviteRoute
  '/connect': typeof ConnectRoute
  '/sign-in': typeof SignInRoute
  '/sign-in-redirect': typeof SignInRedirectRoute
  '/api/$': typeof ApiSplatRoute
  '/install/error': typeof InstallErrorRoute
  '/install/success': typeof InstallSuccessRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/error': typeof OauthErrorRoute
  '/oauth/login': typeof OauthLoginRoute
  '/setup/discord-role': typeof SetupDiscordRoleRoute
  '/setup/jinxxy': typeof SetupJinxxyRoute
  '/setup/lemonsqueezy': typeof SetupLemonsqueezyRoute
  '/setup/payhip': typeof SetupPayhipRoute
  '/setup/vrchat': typeof SetupVrchatRoute
  '/verify/error': typeof VerifyErrorRoute
  '/verify/success': typeof VerifySuccessRoute
  '/account/authorized-apps': typeof AuthenticatedAccountAuthorizedAppsRoute
  '/account/certificates': typeof AuthenticatedAccountCertificatesRoute
  '/account/connections': typeof AuthenticatedAccountConnectionsRoute
  '/account/licenses': typeof AuthenticatedAccountLicensesRoute
  '/account/privacy': typeof AuthenticatedAccountPrivacyRoute
  '/account/verify': typeof AuthenticatedAccountVerifyRoute
  '/dashboard/audit-logs': typeof AuthenticatedDashboardAuditLogsRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/dashboard/certificates': typeof AuthenticatedDashboardCertificatesRoute
  '/dashboard/collaboration': typeof AuthenticatedDashboardCollaborationRoute
  '/dashboard/forensics': typeof AuthenticatedDashboardForensicsRoute
  '/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/dashboard/packages': typeof AuthenticatedDashboardPackagesRoute
  '/dashboard/server-rules': typeof AuthenticatedDashboardServerRulesRoute
  '/verify/purchase': typeof AuthenticatedVerifyPurchaseRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/oauth/callback/itchio': typeof OauthCallbackItchioRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/collab-invite': typeof CollabInviteRoute
  '/connect': typeof ConnectRoute
  '/sign-in': typeof SignInRoute
  '/sign-in-redirect': typeof SignInRedirectRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/install/error': typeof InstallErrorRoute
  '/install/success': typeof InstallSuccessRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/error': typeof OauthErrorRoute
  '/oauth/login': typeof OauthLoginRoute
  '/setup/discord-role': typeof SetupDiscordRoleRoute
  '/setup/jinxxy': typeof SetupJinxxyRoute
  '/setup/lemonsqueezy': typeof SetupLemonsqueezyRoute
  '/setup/payhip': typeof SetupPayhipRoute
  '/setup/vrchat': typeof SetupVrchatRoute
  '/verify/error': typeof VerifyErrorRoute
  '/verify/success': typeof VerifySuccessRoute
  '/_authenticated/account/authorized-apps': typeof AuthenticatedAccountAuthorizedAppsRoute
  '/_authenticated/account/certificates': typeof AuthenticatedAccountCertificatesRoute
  '/_authenticated/account/connections': typeof AuthenticatedAccountConnectionsRoute
  '/_authenticated/account/licenses': typeof AuthenticatedAccountLicensesRoute
  '/_authenticated/account/privacy': typeof AuthenticatedAccountPrivacyRoute
  '/_authenticated/account/verify': typeof AuthenticatedAccountVerifyRoute
  '/_authenticated/dashboard/audit-logs': typeof AuthenticatedDashboardAuditLogsRoute
  '/_authenticated/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/_authenticated/dashboard/certificates': typeof AuthenticatedDashboardCertificatesRoute
  '/_authenticated/dashboard/collaboration': typeof AuthenticatedDashboardCollaborationRoute
  '/_authenticated/dashboard/forensics': typeof AuthenticatedDashboardForensicsRoute
  '/_authenticated/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/_authenticated/dashboard/packages': typeof AuthenticatedDashboardPackagesRoute
  '/_authenticated/dashboard/server-rules': typeof AuthenticatedDashboardServerRulesRoute
  '/_authenticated/verify/purchase': typeof AuthenticatedVerifyPurchaseRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/oauth/callback/itchio': typeof OauthCallbackItchioRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/collab-invite'
    | '/connect'
    | '/sign-in'
    | '/sign-in-redirect'
    | '/account'
    | '/dashboard'
    | '/api/$'
    | '/install/error'
    | '/install/success'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/oauth/consent'
    | '/oauth/error'
    | '/oauth/login'
    | '/setup/discord-role'
    | '/setup/jinxxy'
    | '/setup/lemonsqueezy'
    | '/setup/payhip'
    | '/setup/vrchat'
    | '/verify/error'
    | '/verify/success'
    | '/account/authorized-apps'
    | '/account/certificates'
    | '/account/connections'
    | '/account/licenses'
    | '/account/privacy'
    | '/account/verify'
    | '/dashboard/audit-logs'
    | '/dashboard/billing'
    | '/dashboard/certificates'
    | '/dashboard/collaboration'
    | '/dashboard/forensics'
    | '/dashboard/integrations'
    | '/dashboard/packages'
    | '/dashboard/server-rules'
    | '/verify/purchase'
    | '/api/auth/$'
    | '/oauth/callback/itchio'
    | '/account/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/collab-invite'
    | '/connect'
    | '/sign-in'
    | '/sign-in-redirect'
    | '/api/$'
    | '/install/error'
    | '/install/success'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/oauth/consent'
    | '/oauth/error'
    | '/oauth/login'
    | '/setup/discord-role'
    | '/setup/jinxxy'
    | '/setup/lemonsqueezy'
    | '/setup/payhip'
    | '/setup/vrchat'
    | '/verify/error'
    | '/verify/success'
    | '/account/authorized-apps'
    | '/account/certificates'
    | '/account/connections'
    | '/account/licenses'
    | '/account/privacy'
    | '/account/verify'
    | '/dashboard/audit-logs'
    | '/dashboard/billing'
    | '/dashboard/certificates'
    | '/dashboard/collaboration'
    | '/dashboard/forensics'
    | '/dashboard/integrations'
    | '/dashboard/packages'
    | '/dashboard/server-rules'
    | '/verify/purchase'
    | '/api/auth/$'
    | '/oauth/callback/itchio'
    | '/account'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_authenticated'
    | '/collab-invite'
    | '/connect'
    | '/sign-in'
    | '/sign-in-redirect'
    | '/_authenticated/account'
    | '/_authenticated/dashboard'
    | '/api/$'
    | '/install/error'
    | '/install/success'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/oauth/consent'
    | '/oauth/error'
    | '/oauth/login'
    | '/setup/discord-role'
    | '/setup/jinxxy'
    | '/setup/lemonsqueezy'
    | '/setup/payhip'
    | '/setup/vrchat'
    | '/verify/error'
    | '/verify/success'
    | '/_authenticated/account/authorized-apps'
    | '/_authenticated/account/certificates'
    | '/_authenticated/account/connections'
    | '/_authenticated/account/licenses'
    | '/_authenticated/account/privacy'
    | '/_authenticated/account/verify'
    | '/_authenticated/dashboard/audit-logs'
    | '/_authenticated/dashboard/billing'
    | '/_authenticated/dashboard/certificates'
    | '/_authenticated/dashboard/collaboration'
    | '/_authenticated/dashboard/forensics'
    | '/_authenticated/dashboard/integrations'
    | '/_authenticated/dashboard/packages'
    | '/_authenticated/dashboard/server-rules'
    | '/_authenticated/verify/purchase'
    | '/api/auth/$'
    | '/oauth/callback/itchio'
    | '/_authenticated/account/'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CollabInviteRoute: typeof CollabInviteRoute
  ConnectRoute: typeof ConnectRoute
  SignInRoute: typeof SignInRoute
  SignInRedirectRoute: typeof SignInRedirectRoute
  ApiSplatRoute: typeof ApiSplatRoute
  InstallErrorRoute: typeof InstallErrorRoute
  InstallSuccessRoute: typeof InstallSuccessRoute
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
  LegalTermsOfServiceRoute: typeof LegalTermsOfServiceRoute
  OauthConsentRoute: typeof OauthConsentRoute
  OauthErrorRoute: typeof OauthErrorRoute
  OauthLoginRoute: typeof OauthLoginRoute
  SetupDiscordRoleRoute: typeof SetupDiscordRoleRoute
  SetupJinxxyRoute: typeof SetupJinxxyRoute
  SetupLemonsqueezyRoute: typeof SetupLemonsqueezyRoute
  SetupPayhipRoute: typeof SetupPayhipRoute
  SetupVrchatRoute: typeof SetupVrchatRoute
  VerifyErrorRoute: typeof VerifyErrorRoute
  VerifySuccessRoute: typeof VerifySuccessRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  OauthCallbackItchioRoute: typeof OauthCallbackItchioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in-redirect': {
      id: '/sign-in-redirect'
      path: '/sign-in-redirect'
      fullPath: '/sign-in-redirect'
      preLoaderRoute: typeof SignInRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab-invite': {
      id: '/collab-invite'
      path: '/collab-invite'
      fullPath: '/collab-invite'
      preLoaderRoute: typeof CollabInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/success': {
      id: '/verify/success'
      path: '/verify/success'
      fullPath: '/verify/success'
      preLoaderRoute: typeof VerifySuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/error': {
      id: '/verify/error'
      path: '/verify/error'
      fullPath: '/verify/error'
      preLoaderRoute: typeof VerifyErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/vrchat': {
      id: '/setup/vrchat'
      path: '/setup/vrchat'
      fullPath: '/setup/vrchat'
      preLoaderRoute: typeof SetupVrchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/payhip': {
      id: '/setup/payhip'
      path: '/setup/payhip'
      fullPath: '/setup/payhip'
      preLoaderRoute: typeof SetupPayhipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/lemonsqueezy': {
      id: '/setup/lemonsqueezy'
      path: '/setup/lemonsqueezy'
      fullPath: '/setup/lemonsqueezy'
      preLoaderRoute: typeof SetupLemonsqueezyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/jinxxy': {
      id: '/setup/jinxxy'
      path: '/setup/jinxxy'
      fullPath: '/setup/jinxxy'
      preLoaderRoute: typeof SetupJinxxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/discord-role': {
      id: '/setup/discord-role'
      path: '/setup/discord-role'
      fullPath: '/setup/discord-role'
      preLoaderRoute: typeof SetupDiscordRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/login': {
      id: '/oauth/login'
      path: '/oauth/login'
      fullPath: '/oauth/login'
      preLoaderRoute: typeof OauthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/error': {
      id: '/oauth/error'
      path: '/oauth/error'
      fullPath: '/oauth/error'
      preLoaderRoute: typeof OauthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms-of-service': {
      id: '/legal/terms-of-service'
      path: '/legal/terms-of-service'
      fullPath: '/legal/terms-of-service'
      preLoaderRoute: typeof LegalTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install/success': {
      id: '/install/success'
      path: '/install/success'
      fullPath: '/install/success'
      preLoaderRoute: typeof InstallSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install/error': {
      id: '/install/error'
      path: '/install/error'
      fullPath: '/install/error'
      preLoaderRoute: typeof InstallErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/oauth/callback/itchio': {
      id: '/oauth/callback/itchio'
      path: '/oauth/callback/itchio'
      fullPath: '/oauth/callback/itchio'
      preLoaderRoute: typeof OauthCallbackItchioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/verify/purchase': {
      id: '/_authenticated/verify/purchase'
      path: '/verify/purchase'
      fullPath: '/verify/purchase'
      preLoaderRoute: typeof AuthenticatedVerifyPurchaseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/server-rules': {
      id: '/_authenticated/dashboard/server-rules'
      path: '/server-rules'
      fullPath: '/dashboard/server-rules'
      preLoaderRoute: typeof AuthenticatedDashboardServerRulesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/packages': {
      id: '/_authenticated/dashboard/packages'
      path: '/packages'
      fullPath: '/dashboard/packages'
      preLoaderRoute: typeof AuthenticatedDashboardPackagesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/integrations': {
      id: '/_authenticated/dashboard/integrations'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof AuthenticatedDashboardIntegrationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/forensics': {
      id: '/_authenticated/dashboard/forensics'
      path: '/forensics'
      fullPath: '/dashboard/forensics'
      preLoaderRoute: typeof AuthenticatedDashboardForensicsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/collaboration': {
      id: '/_authenticated/dashboard/collaboration'
      path: '/collaboration'
      fullPath: '/dashboard/collaboration'
      preLoaderRoute: typeof AuthenticatedDashboardCollaborationRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/certificates': {
      id: '/_authenticated/dashboard/certificates'
      path: '/certificates'
      fullPath: '/dashboard/certificates'
      preLoaderRoute: typeof AuthenticatedDashboardCertificatesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/billing': {
      id: '/_authenticated/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AuthenticatedDashboardBillingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/audit-logs': {
      id: '/_authenticated/dashboard/audit-logs'
      path: '/audit-logs'
      fullPath: '/dashboard/audit-logs'
      preLoaderRoute: typeof AuthenticatedDashboardAuditLogsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/account/verify': {
      id: '/_authenticated/account/verify'
      path: '/verify'
      fullPath: '/account/verify'
      preLoaderRoute: typeof AuthenticatedAccountVerifyRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/privacy': {
      id: '/_authenticated/account/privacy'
      path: '/privacy'
      fullPath: '/account/privacy'
      preLoaderRoute: typeof AuthenticatedAccountPrivacyRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/licenses': {
      id: '/_authenticated/account/licenses'
      path: '/licenses'
      fullPath: '/account/licenses'
      preLoaderRoute: typeof AuthenticatedAccountLicensesRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/connections': {
      id: '/_authenticated/account/connections'
      path: '/connections'
      fullPath: '/account/connections'
      preLoaderRoute: typeof AuthenticatedAccountConnectionsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/certificates': {
      id: '/_authenticated/account/certificates'
      path: '/certificates'
      fullPath: '/account/certificates'
      preLoaderRoute: typeof AuthenticatedAccountCertificatesRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/authorized-apps': {
      id: '/_authenticated/account/authorized-apps'
      path: '/authorized-apps'
      fullPath: '/account/authorized-apps'
      preLoaderRoute: typeof AuthenticatedAccountAuthorizedAppsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountAuthorizedAppsRoute: typeof AuthenticatedAccountAuthorizedAppsRoute
  AuthenticatedAccountCertificatesRoute: typeof AuthenticatedAccountCertificatesRoute
  AuthenticatedAccountConnectionsRoute: typeof AuthenticatedAccountConnectionsRoute
  AuthenticatedAccountLicensesRoute: typeof AuthenticatedAccountLicensesRoute
  AuthenticatedAccountPrivacyRoute: typeof AuthenticatedAccountPrivacyRoute
  AuthenticatedAccountVerifyRoute: typeof AuthenticatedAccountVerifyRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountAuthorizedAppsRoute:
    AuthenticatedAccountAuthorizedAppsRoute,
  AuthenticatedAccountCertificatesRoute: AuthenticatedAccountCertificatesRoute,
  AuthenticatedAccountConnectionsRoute: AuthenticatedAccountConnectionsRoute,
  AuthenticatedAccountLicensesRoute: AuthenticatedAccountLicensesRoute,
  AuthenticatedAccountPrivacyRoute: AuthenticatedAccountPrivacyRoute,
  AuthenticatedAccountVerifyRoute: AuthenticatedAccountVerifyRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAuditLogsRoute: typeof AuthenticatedDashboardAuditLogsRoute
  AuthenticatedDashboardBillingRoute: typeof AuthenticatedDashboardBillingRoute
  AuthenticatedDashboardCertificatesRoute: typeof AuthenticatedDashboardCertificatesRoute
  AuthenticatedDashboardCollaborationRoute: typeof AuthenticatedDashboardCollaborationRoute
  AuthenticatedDashboardForensicsRoute: typeof AuthenticatedDashboardForensicsRoute
  AuthenticatedDashboardIntegrationsRoute: typeof AuthenticatedDashboardIntegrationsRoute
  AuthenticatedDashboardPackagesRoute: typeof AuthenticatedDashboardPackagesRoute
  AuthenticatedDashboardServerRulesRoute: typeof AuthenticatedDashboardServerRulesRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAuditLogsRoute: AuthenticatedDashboardAuditLogsRoute,
    AuthenticatedDashboardBillingRoute: AuthenticatedDashboardBillingRoute,
    AuthenticatedDashboardCertificatesRoute:
      AuthenticatedDashboardCertificatesRoute,
    AuthenticatedDashboardCollaborationRoute:
      AuthenticatedDashboardCollaborationRoute,
    AuthenticatedDashboardForensicsRoute: AuthenticatedDashboardForensicsRoute,
    AuthenticatedDashboardIntegrationsRoute:
      AuthenticatedDashboardIntegrationsRoute,
    AuthenticatedDashboardPackagesRoute: AuthenticatedDashboardPackagesRoute,
    AuthenticatedDashboardServerRulesRoute:
      AuthenticatedDashboardServerRulesRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedVerifyPurchaseRoute: typeof AuthenticatedVerifyPurchaseRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedVerifyPurchaseRoute: AuthenticatedVerifyPurchaseRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CollabInviteRoute: CollabInviteRoute,
  ConnectRoute: ConnectRoute,
  SignInRoute: SignInRoute,
  SignInRedirectRoute: SignInRedirectRoute,
  ApiSplatRoute: ApiSplatRoute,
  InstallErrorRoute: InstallErrorRoute,
  InstallSuccessRoute: InstallSuccessRoute,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
  LegalTermsOfServiceRoute: LegalTermsOfServiceRoute,
  OauthConsentRoute: OauthConsentRoute,
  OauthErrorRoute: OauthErrorRoute,
  OauthLoginRoute: OauthLoginRoute,
  SetupDiscordRoleRoute: SetupDiscordRoleRoute,
  SetupJinxxyRoute: SetupJinxxyRoute,
  SetupLemonsqueezyRoute: SetupLemonsqueezyRoute,
  SetupPayhipRoute: SetupPayhipRoute,
  SetupVrchatRoute: SetupVrchatRoute,
  VerifyErrorRoute: VerifyErrorRoute,
  VerifySuccessRoute: VerifySuccessRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  OauthCallbackItchioRoute: OauthCallbackItchioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
