console.log(
  JSON.stringify({
    FRONTEND_URL: process.env.FRONTEND_URL,
    HYPERDX_APP_URL: process.env.HYPERDX_APP_URL,
    HYPERDX_OTLP_HTTP_URL: process.env.HYPERDX_OTLP_HTTP_URL,
    HYPERDX_OTLP_GRPC_URL: process.env.HYPERDX_OTLP_GRPC_URL,
    OTEL_EXPORTER_OTLP_ENDPOINT: process.env.OTEL_EXPORTER_OTLP_ENDPOINT,
    OTEL_EXPORTER_OTLP_PROTOCOL: process.env.OTEL_EXPORTER_OTLP_PROTOCOL,
  })
);
